# config/application.yml
defaults: &defaults



development:
  <<: *defaults
  api_host: http://pairwise-api.localisto.net
  api_user_email: localisto@localisto.org
  api_user_password: 8FA79096C01

test:
  <<: *defaults

production:
  <<: *defaults